#!/usr/bin/env bash
# betterbirdPatcher.sh
# Patches Betterbird chrome with the accent color.
# Usage: betterbirdPatcher.sh <hex_color>

color="${1,,}"

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color>" >&2
    exit 1
fi

accent="#$color"

TB_ROOT="$HOME/.thunderbird"
PROFILES_INI="$TB_ROOT/profiles.ini"

if [ ! -f "$PROFILES_INI" ]; then
    echo "No Betterbird profiles.ini found at $PROFILES_INI"
    exit 0
fi

# Profile folder names (like "8ma66p8a.default-release") are randomly
# generated per-install — hardcoding them only ever works on the one
# machine they were captured from. profiles.ini is Betterbird/Thunderbird's
# own record of every real profile it has, each with an IsRelative/Path
# pair; read that instead of guessing. Awk resets its captured Path/IsRelative
# on every new [section] header, so multi-line INI sections in any order
# are handled correctly regardless of how many profiles exist.
while IFS=$'\t' read -r is_relative path; do
    [ -n "$path" ] || continue

    if [ "$is_relative" = "0" ]; then
        TB_PROFILE="$path"
    else
        TB_PROFILE="$TB_ROOT/$path"
    fi

    [ -d "$TB_PROFILE" ] || continue

    mkdir -p "$TB_PROFILE/chrome"
    cat > "$TB_PROFILE/chrome/userChrome.css" << EOF
/* Generated by themeRefresher */
:root {
    --lwt-accent-color: $accent !important;
    --toolbar-field-focus-border-color: $accent !important;
    --toolbar-field-color: #fcfcfc !important;
    --toolbar-field-focus-color: #fcfcfc !important;
    --toolbar-color: #fcfcfc !important;
    --sidebar-highlight-background-color: $accent !important;
    --selected-item-color: $accent !important;
}

/* folder pane selected folder */
#folderTree tr.selected,
treechildren::-moz-tree-row(selected) {
    background-color: $accent !important;
}

/* thread pane — table view */
tr[is="thread-row"].selected {
    background-color: $accent !important;
    color: #fcfcfc !important;
}

/* thread pane — card view */
tr[is="thread-card"].selected .card-container {
    background-color: $accent !important;
    color: #fcfcfc !important;
}

::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    cat > "$TB_PROFILE/chrome/userContent.css" << EOF
/* Generated by themeRefresher */
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    grep -q "toolkit.legacyUserProfileCustomizations.stylesheets" "$TB_PROFILE/prefs.js" 2>/dev/null || \
        echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$TB_PROFILE/prefs.js"
    echo "Betterbird profile patched: $TB_PROFILE"
done < <(awk '
    /^\[/ {
        if (path != "") print relative "\t" path
        path = ""; relative = "1"
        next
    }
    /^Path=/     { path = substr($0, 6) }
    /^IsRelative=/ { relative = substr($0, 12) }
    END { if (path != "") print relative "\t" path }
' "$PROFILES_INI")