#!/usr/bin/env bash
# firefoxPatcher.sh
# Patches Firefox chrome (userChrome/userContent CSS) with the accent color
# for every profile listed in profiles.ini.
# Usage: firefoxPatcher.sh <hex_color>

color="${1,,}"

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color>" >&2
    exit 1
fi

accent="#$color"

firefoxRoot="$HOME/.mozilla/firefox"
profilesIniFile="$firefoxRoot/profiles.ini"

if [ ! -f "$profilesIniFile" ]; then
    echo "No Firefox profiles.ini found at $profilesIniFile" >&2
    exit 1
fi

# Collect profile paths from profiles.ini (handles both [Profile*] and
# [Install*] Default= entries; relative paths are relative to firefoxRoot).
mapfile -t profileDirs < <(
    awk -F= '
        /^\[Profile/ { inBlock=1 }
        /^\[Install/ { inBlock=1 }
        /^\[/ && !/^\[Profile/ && !/^\[Install/ { inBlock=0 }
        inBlock && $1=="Path"    { print $2 }
        inBlock && $1=="Default" { print $2 }
    ' "$profilesIniFile" | sort -u
)

if [ "${#profileDirs[@]}" -eq 0 ]; then
    echo "No profiles found in $profilesIniFile" >&2
    exit 1
fi

patchedCount=0
for relPath in "${profileDirs[@]}"; do
    if [[ "$relPath" = /* ]]; then
        profileDir="$relPath"
    else
        profileDir="$firefoxRoot/$relPath"
    fi

    [ ! -d "$profileDir" ] && continue

    mkdir -p "$profileDir/chrome"
    cat > "$profileDir/chrome/userChrome.css" << EOF
/* Generated by themeRefresher */
:root {
    --lwt-accent-color: $accent !important;
    --toolbar-field-focus-border-color: $accent !important;
    --toolbar-field-color: #fcfcfc !important;
    --toolbar-field-focus-color: #fcfcfc !important;
    --toolbar-color: #fcfcfc !important;
    --urlbar-box-text-color: #fcfcfc !important;
}
#urlbar-input { color: #fcfcfc !important; }
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    cat > "$profileDir/chrome/userContent.css" << EOF
/* Generated by themeRefresher */
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    grep -q "toolkit.legacyUserProfileCustomizations.stylesheets" "$profileDir/prefs.js" 2>/dev/null || \
        echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$profileDir/prefs.js"

    echo "Firefox profile patched: $profileDir"
    patchedCount=$((patchedCount + 1))
done

if [ "$patchedCount" -eq 0 ]; then
    echo "No valid Firefox profile directories found on disk." >&2
    exit 1
fi

echo "Restart Firefox (or reload with Ctrl+Shift+R after toggling the pref) for changes to fully apply."