#!/usr/bin/env bash
# firefoxPatcher.sh
# Patches Firefox chrome with the accent color.
# Usage: firefoxPatcher.sh <hex_color>

color="${1,,}"

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color>" >&2
    exit 1
fi

accent="#$color"

FIREFOX_ROOT="$HOME/.mozilla/firefox"
INI="$FIREFOX_ROOT/profiles.ini"

if [ ! -f "$INI" ]; then
    echo "No Firefox profiles.ini found at $INI" >&2
    exit 1
fi

# Collect profile paths from profiles.ini (handles both [Profile*] and
# [Install*] Default= entries; relative paths are relative to FIREFOX_ROOT).
mapfile -t PROFILE_DIRS < <(
    awk -F= '
        /^\[Profile/ { in_block=1 }
        /^\[Install/ { in_block=1 }
        /^\[/ && !/^\[Profile/ && !/^\[Install/ { in_block=0 }
        in_block && $1=="Path"    { print $2 }
        in_block && $1=="Default" { print $2 }
    ' "$INI" | sort -u
)

if [ "${#PROFILE_DIRS[@]}" -eq 0 ]; then
    echo "No profiles found in $INI" >&2
    exit 1
fi

patched=0
for rel in "${PROFILE_DIRS[@]}"; do
    if [[ "$rel" = /* ]]; then
        PROFILE="$rel"
    else
        PROFILE="$FIREFOX_ROOT/$rel"
    fi

    [ ! -d "$PROFILE" ] && continue

    mkdir -p "$PROFILE/chrome"
    cat > "$PROFILE/chrome/userChrome.css" << EOF
/* Generated by themeRefresher */
:root {
    --lwt-accent-color: $accent !important;
    --toolbar-field-focus-border-color: $accent !important;
    --toolbar-field-color: #fcfcfc !important;
    --toolbar-field-focus-color: #fcfcfc !important;
    --toolbar-color: #fcfcfc !important;
    --urlbar-box-text-color: #fcfcfc !important;
}
#urlbar-input { color: #fcfcfc !important; }
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    cat > "$PROFILE/chrome/userContent.css" << EOF
/* Generated by themeRefresher */
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    grep -q "toolkit.legacyUserProfileCustomizations.stylesheets" "$PROFILE/prefs.js" 2>/dev/null || \
        echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$PROFILE/prefs.js"

    echo "Firefox profile patched: $PROFILE"
    patched=$((patched + 1))
done

if [ "$patched" -eq 0 ]; then
    echo "No valid Firefox profile directories found on disk." >&2
    exit 1
fi

echo "Restart Firefox (or reload with Ctrl+Shift+R after toggling the pref) for changes to fully apply."
