#!/usr/bin/env bash
# thunderbirdPatcher.sh
# Patches Thunderbird/Betterbird chrome with the accent color for every
# profile listed in profiles.ini.
# Usage: thunderbirdPatcher.sh <hex_color>

color="${1,,}"

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color>" >&2
    exit 1
fi

accent="#$color"

tbRoot="$HOME/.thunderbird"
profilesIniFile="$tbRoot/profiles.ini"

if [ ! -f "$profilesIniFile" ]; then
    echo "No Betterbird/Thunderbird profiles.ini found at $profilesIniFile"
    exit 0
fi

# Profile folder names are randomly generated per-install, so read the
# real Path/IsRelative pairs from profiles.ini rather than guessing them.
while IFS=$'\t' read -r isRelative relPath; do
    [ -n "$relPath" ] || continue

    if [ "$isRelative" = "0" ]; then
        profileDir="$relPath"
    else
        profileDir="$tbRoot/$relPath"
    fi

    [ -d "$profileDir" ] || continue

    mkdir -p "$profileDir/chrome"
    cat > "$profileDir/chrome/userChrome.css" << EOF
/* Generated by themeRefresher */
:root {
    --lwt-accent-color: $accent !important;
    --toolbar-field-focus-border-color: $accent !important;
    --toolbar-field-color: #fcfcfc !important;
    --toolbar-field-focus-color: #fcfcfc !important;
    --toolbar-color: #fcfcfc !important;
    --sidebar-highlight-background-color: $accent !important;
    --selected-item-color: $accent !important;
}

/* folder pane selected folder */
#folderTree tr.selected,
treechildren::-moz-tree-row(selected) {
    background-color: $accent !important;
}

/* thread pane — table view */
tr[is="thread-row"].selected {
    background-color: $accent !important;
    color: #fcfcfc !important;
}

/* thread pane — card view */
tr[is="thread-card"].selected .card-container {
    background-color: $accent !important;
    color: #fcfcfc !important;
}

::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    cat > "$profileDir/chrome/userContent.css" << EOF
/* Generated by themeRefresher */
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    grep -q "toolkit.legacyUserProfileCustomizations.stylesheets" "$profileDir/prefs.js" 2>/dev/null || \
        echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$profileDir/prefs.js"
    echo "Betterbird/Thunderbird profile patched: $profileDir"
done < <(awk '
    /^\[/ {
        if (path != "") print relative "\t" path
        path = ""; relative = "1"
        next
    }
    /^Path=/     { path = substr($0, 6) }
    /^IsRelative=/ { relative = substr($0, 12) }
    END { if (path != "") print relative "\t" path }
' "$profilesIniFile")