#!/usr/bin/env bash
# zenPatcher.sh
# Patches Zen Browser chrome with the accent color.
# Usage: zenPatcher.sh <hex_color>

color="${1,,}"

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color>" >&2
    exit 1
fi

accent="#$color"

ZEN_ROOT="$HOME/.zen"
PROFILES_INI="$ZEN_ROOT/profiles.ini"

if [ ! -f "$PROFILES_INI" ]; then
    echo "No Zen profiles.ini found at $PROFILES_INI"
    exit 0
fi

# Profile folder names (like "8ma66p8a.Default (release)") are randomly
# generated per-install — hardcoding them only ever works on the one
# machine they were captured from. profiles.ini is Zen/Firefox's own
# record of every real profile it has, each with an IsRelative/Path pair;
# read that instead of guessing. Awk resets its captured Path/IsRelative
# on every new [section] header, so multi-line INI sections in any order
# are handled correctly regardless of how many profiles exist.
while IFS=$'\t' read -r is_relative path; do
    [ -n "$path" ] || continue

    if [ "$is_relative" = "0" ]; then
        ZEN_PROFILE="$path"
    else
        ZEN_PROFILE="$ZEN_ROOT/$path"
    fi

    [ -d "$ZEN_PROFILE" ] || continue

    mkdir -p "$ZEN_PROFILE/chrome"
    cat > "$ZEN_PROFILE/chrome/userChrome.css" << EOF
/* Generated by themeRefresher */
:root {
    --lwt-accent-color: $accent !important;
    --toolbar-field-focus-border-color: $accent !important;
    --toolbar-field-color: #fcfcfc !important;
    --toolbar-field-focus-color: #fcfcfc !important;
    --toolbar-color: #fcfcfc !important;
    --urlbar-box-text-color: #fcfcfc !important;
}
#urlbar-input { color: #fcfcfc !important; }
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    cat > "$ZEN_PROFILE/chrome/userContent.css" << EOF
/* Generated by themeRefresher */
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    grep -q "toolkit.legacyUserProfileCustomizations.stylesheets" "$ZEN_PROFILE/prefs.js" 2>/dev/null || \
        echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$ZEN_PROFILE/prefs.js"
    echo "Zen profile patched: $ZEN_PROFILE"
done < <(awk '
    /^\[/ {
        if (path != "") print relative "\t" path
        path = ""; relative = "1"
        next
    }
    /^Path=/     { path = substr($0, 6) }
    /^IsRelative=/ { relative = substr($0, 12) }
    END { if (path != "") print relative "\t" path }
' "$PROFILES_INI")