#!/usr/bin/env bash
# trayIconPatcher.sh
# Themes system-tray icons for apps that don't pick up breeze-dark-accent's
# regular app-icon theming automatically — either because they draw their
# tray icon from their own bundled asset (not looked up by name through the
# icon theme), or because they expect a literal file path in their own
# config the way Vesktop does.
#
# Split out from iconPatcher.sh because these apps each need a different,
# fairly hand-rolled approach rather than the generic .desktop-driven engine.
#
# Usage: trayIconPatcher.sh <hex_color> [--list]
#   --list   only discover/report what would be touched for blueman and
#            onedrivegui (no files written). Use this first on a new
#            machine to confirm the discovered icon names look right
#            before doing a real run.
#
# Called automatically from iconPatcher.sh at the very end of its run, so
# the accent-colored app SVGs in $ICON_DIR/apps/scalable/ already exist by
# the time this runs.

color="${1,,}"
LIST_ONLY=0
[ "${2:-}" = "--list" ] && LIST_ONLY=1

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color> [--list]" >&2
    exit 1
fi

accent="#$color"
SUPPORT="$HOME/.config/WallpaperChanger/themeRefresherSupportScripts"
ICONS="$SUPPORT/svg"
GAME_ICONS="$ICONS/games"
ICON_DIR="$HOME/.local/share/icons/breeze-dark-accent"

# ---------------------------------------------------------------------------
# Match waybar's text color exactly, not just "the same seed".
#
# $color/$accent here is the raw hex colorChooser.sh sampled from the
# wallpaper. But waybar's @primary (used for textcolor2 in ML4W-modern.css,
# and for accents throughout the other themes since the InioX template
# migration) is matugen's *resolved* colors.primary.default — a
# tonally-adjusted Material/HCT derivative of that seed, not the seed
# itself. Icons colored with the raw seed and waybar text colored with the
# resolved primary are two different colors that happen to be close, which
# is exactly why the mismatch was "extremely visible" sitting right next
# to each other in the tray. Since matugen already runs before
# iconPatcher.sh in themeRefresher.sh, the rendered file already has the
# real value — read it back rather than re-deriving it here.
#
# NOTE: since migrating the waybar template to InioX/matugen-themes, the
# rendered file moved from .config/waybar/matugen/colors-waybar.css to
# .config/waybar/colors.css, and the role once called "color4" (raw
# colors.primary.default.hex) is now just named "primary" — same value,
# new name.
#
# Only affects tray icons. Everything else in the pipeline (breeze theme,
# KDE colorscheme, GTK, RGB devices) still uses the raw seed as before.
WAYBAR_COLORS_RENDERED="$HOME/.config/waybar/colors.css"
if [ -f "$WAYBAR_COLORS_RENDERED" ]; then
    waybar_accent=$(grep -m1 -oP '@define-color\s+primary\s+\K#[0-9a-fA-F]{6}' "$WAYBAR_COLORS_RENDERED")
    if [ -n "$waybar_accent" ]; then
        accent="$waybar_accent"
        color="${accent#\#}"
        color="${color,,}"
        echo "  tray icons: using waybar's resolved primary ($accent) instead of the raw wallpaper seed"
    else
        echo "  tray icons: primary not found in $WAYBAR_COLORS_RENDERED, falling back to raw seed color"
    fi
else
    echo "  tray icons: $WAYBAR_COLORS_RENDERED not found, falling back to raw seed color"
fi

# ---------------------------------------------------------------------------
# Shared helper — always recolors fresh from the base SVG using THIS
# script's own $accent (which by this point has already been corrected to
# match waybar's resolved primary, see above). Deliberately does NOT reuse
# $ICON_DIR/apps/scalable/<name>.svg even when it exists — that copy was
# generated by iconPatcher.sh's main engine using the raw wallpaper-seed
# accent (iconPatcher.sh runs and finishes before this script even starts
# computing its own corrected value), so reusing it would silently defeat
# the primary correction for every tray icon that calls this. Costs a
# redundant recolor of files iconPatcher.sh already colored once, but
# guarantees tray icons and waybar text always agree.
# ---------------------------------------------------------------------------
resolve_themed_svg() {
    local name="$1"
    local base=""
    [ -f "$GAME_ICONS/${name}_base_icon.svg" ] && base="$GAME_ICONS/${name}_base_icon.svg"
    [ -z "$base" ] && [ -f "$ICONS/${name}_base_icon.svg" ] && base="$ICONS/${name}_base_icon.svg"
    [ -z "$base" ] && return 1

    local tmp
    tmp=$(mktemp --suffix=.svg)
    sed "s/currentColor/$accent/g" "$base" > "$tmp"
    echo "$tmp"
}

# fix_system_dir_permissions <dir> <label>
# One-time chown of a package-owned directory to the current user, so
# subsequent writes need no sudo at all — until the next package update
# resets ownership back to root, at which point this just redoes it.
# Non-blocking: uses `sudo -n`, so it fails fast instead of hanging when
# there's no cached credential/interactive terminal (see: the hang bug
# from an earlier version of this pattern). Ownership is otherwise kept
# in sync by TARGETS in update-and-fix.sh, which runs after every
# topgrade and re-chowns anything a package update reset to root.
fix_system_dir_permissions() {
    local dir="$1" label="$2"
    [ -w "$dir" ] && return 0
    echo "  $label: $dir is root-owned, attempting one-time chown..."
    if sudo -n chown -R "$USER" "$dir" 2>/dev/null; then
        echo "  $label: ownership fixed — future runs won't need sudo."
        echo "  (if theming silently stops updating after a $label package"
        echo "   update, that's this directory getting reset to root again — just"
        echo "   re-run this script and it'll redo the chown.)"
        return 0
    fi
    echo "  $label: couldn't chown automatically (needs an interactive sudo prompt)."
    echo "  Run this once yourself, then re-run this script:"
    echo "    sudo chown -R \$USER $dir"
    return 1
}

#nativmix tray icon
patch_nativmix_tray() {
    command -v nativmix >/dev/null 2>&1 || return 0

    # Confirmed via nativmix's own source (utils/paths.py get_icon_path()):
    # the tray icon always reads this exact file directly, and only falls
    # back to QIcon.fromTheme("nativmix") if it's missing — so as long as
    # this file exists (it does, via the AUR package), theming the icon
    # theme entry alone is never enough; this file has to be overwritten.
    local target="/usr/share/nativmix/assets/icon.png"
    [ -f "$target" ] || {
        echo "  nativmix: $target not found (package layout may have changed)"
        return 1
    }

    local svg
    svg=$(resolve_themed_svg "nativmix-alt") || svg=$(resolve_themed_svg "nativmix") || {
        echo "  nativmix: no themed base icon found, skipping tray"; return 1
    }

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "nativmix: would overwrite $target with themed nativmix-alt/nativmix icon"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  nativmix: rsvg-convert not found, cannot rasterize"; return 1
    }

    fix_system_dir_permissions "$(dirname "$target")" "nativmix" || return 1

    local backup="${target}.orig"
    [ -f "$backup" ] || cp "$target" "$backup"

    rsvg-convert -w 256 -h 256 "$svg" -o "$target" \
        && echo "NativMix tray icon patched in place ($target)"
}

#ferdium tray icon
patch_ferdium_tray() {
    command -v ferdium >/dev/null 2>&1 || return 0

    # Confirmed via `pacman -Ql ferdium-bin`: real Linux tray assets bundled
    # at this path, root-owned (AUR package installs to /opt). No per-user
    # config indirection like Vesktop's trayIconPath — these files are what
    # Ferdium actually loads.
    local tray_dir="/opt/ferdium-bin/assets/images/tray/linux"
    [ -d "$tray_dir" ] || {
        echo "  ferdium: $tray_dir not found (package layout may have changed)"
        return 1
    }

    local svg
    svg=$(resolve_themed_svg "ferdium") || { echo "  ferdium: no themed base icon found, skipping tray"; return 1; }

    # tray/tray-indirect/tray-unread all get the same plain accent icon —
    # Ferdium doesn't expose a separate unread-badge asset to composite
    # onto here the way Vesktop's settings.json flow does. Say the word if
    # you'd like a red-dot badge burned into tray-unread.png specifically.
    local names=(tray tray-indirect tray-unread)

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "ferdium: would overwrite in $tray_dir:"
        for n in "${names[@]}"; do
            printf '  %s.png / %s@2x.png\n' "$n" "$n"
        done
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  ferdium: rsvg-convert not found, cannot rasterize"; return 1
    }
    fix_system_dir_permissions "$tray_dir" "ferdium" || return 1

    local patched=0
    local job_dir
    job_dir=$(mktemp -d)
    local i=0
    for n in "${names[@]}"; do
        for variant in "$n.png" "$n@2x.png"; do
            local f="$tray_dir/$variant"
            [ -f "$f" ] || continue
            i=$((i + 1))
            (
                backup="${f}.orig"
                [ -f "$backup" ] || cp "$f" "$backup"

                if command -v identify >/dev/null 2>&1; then
                    dims=$(identify -format "%wx%h" "$backup" 2>/dev/null)
                elif command -v magick >/dev/null 2>&1; then
                    dims=$(magick identify -format "%wx%h" "$backup" 2>/dev/null)
                fi
                size="${dims%x*}"
                [ -z "$size" ] && size=22

                rsvg-convert -w "$size" -h "$size" "$svg" -o "$f" && touch "$job_dir/$i"
            ) &
        done
    done
    wait
    patched=$(find "$job_dir" -mindepth 1 | wc -l)
    rm -rf "$job_dir"
    echo "Ferdium tray icons patched in place ($patched files, $tray_dir)"
}

#localsend tray icon
patch_localsend_tray() {
    command -v localsend >/dev/null 2>&1 || return 0

    # Confirmed via `pacman -Ql localsend`: real tray assets live in its
    # Flutter asset bundle. logo-32-black/-white are the light/dark tray
    # variants (standard cross-platform tray convention); logo-32.png is
    # the plain fallback. Recolor all three since we can't tell at rest
    # which one LocalSend's tray plugin actually selects at runtime.
    local img_dir="/usr/lib/localsend/data/flutter_assets/assets/img"
    [ -d "$img_dir" ] || {
        echo "  localsend: $img_dir not found (package layout may have changed)"
        return 1
    }

    local svg
    svg=$(resolve_themed_svg "localsend") || { echo "  localsend: no themed base icon found, skipping tray"; return 1; }

    local names=(logo-32.png logo-32-black.png logo-32-white.png)

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "localsend: would overwrite in $img_dir:"
        printf '  %s\n' "${names[@]}"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  localsend: rsvg-convert not found, cannot rasterize"; return 1
    }
    fix_system_dir_permissions "$img_dir" "localsend" || return 1

    local patched=0
    for n in "${names[@]}"; do
        local f="$img_dir/$n"
        [ -f "$f" ] || continue
        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"
        rsvg-convert -w 32 -h 32 "$svg" -o "$f" && patched=$((patched + 1))
    done
    echo "LocalSend tray icons patched in place ($patched/${#names[@]}, $img_dir)"
}

#streamcontroller tray icon
patch_streamcontroller_tray() {
    command -v streamcontroller >/dev/null 2>&1 || return 0

    # Confirmed via src/tray.py: it sets its own DBus StatusNotifierItem
    # IconThemePath to /usr/lib/streamcontroller/Assets/icons (bypassing
    # the active icon theme entirely) and requests icon name
    # "com.core447.StreamController" — which resolves to exactly these two
    # files, per the standard hicolor apps/<size> layout.
    local icon_base="/usr/lib/streamcontroller/Assets/icons/hicolor"
    local targets=(
        "$icon_base/48x48/apps/com.core447.StreamController.png"
        "$icon_base/512x512/apps/com.core447.StreamController.png"
    )

    local svg
    svg=$(resolve_themed_svg "elgato") || { echo "  streamcontroller: no themed base icon found, skipping tray"; return 1; }

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "streamcontroller: would overwrite:"
        printf '  %s\n' "${targets[@]}"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  streamcontroller: rsvg-convert not found, cannot rasterize"; return 1
    }
    fix_system_dir_permissions "$icon_base" "streamcontroller" || return 1

    local patched=0
    for f in "${targets[@]}"; do
        [ -f "$f" ] || { echo "  streamcontroller: $f not found, skipping"; continue; }
        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"
        # Size comes from the directory name (48x48 / 512x512).
        local size
        size=$(basename "$(dirname "$(dirname "$f")")")
        size="${size%%x*}"
        rsvg-convert -w "$size" -h "$size" "$svg" -o "$f" && patched=$((patched + 1))
    done
    echo "StreamController tray icon patched in place ($patched/${#targets[@]})"
}

#steam tray icon
patch_steam_tray() {
    command -v steam >/dev/null 2>&1 || return 0

    local svg
    svg=$(resolve_themed_svg "steam") || { echo "  steam: no themed base icon found, skipping tray"; return 1; }

    local targets=(
        "$HOME/.local/share/Steam/public/steam_tray_mono.png"
        "/usr/share/pixmaps/steam_tray_mono.png"
    )

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "steam: would overwrite:"
        printf '  %s\n' "${targets[@]}"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  steam: rsvg-convert not found, cannot rasterize"; return 1
    }

    local patched=0
    for f in "${targets[@]}"; do
        [ -f "$f" ] || { echo "  steam: $f not found, skipping"; continue; }

        # Only the system copy needs the chown-once treatment; the
        # self-updating client copy under $HOME is already user-owned.
        if [[ "$f" == /usr/* ]]; then
            fix_system_dir_permissions "$(dirname "$f")" "steam" || continue
        fi

        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"

        local dims size
        if command -v identify >/dev/null 2>&1; then
            dims=$(identify -format "%wx%h" "$backup" 2>/dev/null)
        elif command -v magick >/dev/null 2>&1; then
            dims=$(magick identify -format "%wx%h" "$backup" 2>/dev/null)
        fi
        size="${dims%x*}"
        [ -z "$size" ] && size=24

        rsvg-convert -w "$size" -h "$size" "$svg" -o "$f" && patched=$((patched + 1))
    done
    echo "Steam tray icon patched in place ($patched/${#targets[@]})"
}

#blueman tray icon
patch_blueman_tray() {
    command -v blueman-applet >/dev/null 2>&1 || return 0

    local search_dirs=(
        "/usr/share/icons/hicolor"
        "/usr/share/pixmaps"
        "/usr/share/blueman/icons"
    )
    local found=()
    for dir in "${search_dirs[@]}"; do
        [ -d "$dir" ] || continue
        while IFS= read -r f; do
            found+=("$f")
        done < <(find "$dir" -iname "*blueman-tray*" -type f 2>/dev/null)
    done

    if [ "${#found[@]}" -eq 0 ]; then
        echo "  blueman: no blueman-tray-* icon files found under ${search_dirs[*]}"
        echo "  (run 'find / -iname \"*blueman-tray*\" 2>/dev/null' once to locate them,"
        echo "   then adjust search_dirs in patch_blueman_tray)"
        return 1
    fi

    # Full substitution with the same bluetooth icon already used for the
    # "Bluetooth Manager" app icon elsewhere in iconPatcher.sh, rather than
    # tinting blueman's own vendor art — vendor blueman-tray icons are a
    # filled badge shape, so a plain -colorize just turns into a flat blob
    # instead of a recognizable glyph.
    local src_svg
    src_svg=$(resolve_themed_svg "bluetooth") || {
        echo "  blueman: $ICONS/bluetooth_base_icon.svg not found, can't substitute — falling back to plain recolor"
        src_svg=""
    }

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "blueman: would replace ${#found[@]} file(s) with bluetooth_base_icon.svg:"
        printf '  %s\n' "${found[@]}"
        return 0
    fi

    local tool=""
    command -v magick >/dev/null 2>&1 && tool="magick"
    [ -z "$tool" ] && command -v convert >/dev/null 2>&1 && tool="convert"

    local tmp_svg=""
    if [ -n "$src_svg" ]; then
        # resolve_themed_svg already returns accent-colored content (either
        # the engine's already-generated app icon, or a freshly recolored
        # temp copy of the base SVG) — just use it directly.
        tmp_svg="$src_svg"
    fi

    local patched=0
    local job_dir
    job_dir=$(mktemp -d)
    local i=0
    for f in "${found[@]}"; do
        i=$((i + 1))
        (
            case "$f" in
                *hicolor*)
                    rel="${f#/usr/share/icons/hicolor/}"
                    dst="$ICON_DIR/$rel"
                    ;;
                *)
                    # pixmaps/blueman's own dir — no theme-relative path, so
                    # just mirror basename under a flat "blueman" subfolder.
                    dst="$ICON_DIR/blueman/$(basename "$f")"
                    ;;
            esac
            mkdir -p "$(dirname "$dst")"

            if [ -n "$tmp_svg" ]; then
                if [[ "$f" == *.svg ]]; then
                    cp "$tmp_svg" "$dst"
                elif command -v rsvg-convert >/dev/null 2>&1; then
                    # Size comes from the hicolor directory name (e.g. 24x24);
                    # default to 48 for anything outside that layout (pixmaps).
                    size=48
                    if [[ "$f" == *hicolor/*x*/status* ]]; then
                        sizedir="${f#/usr/share/icons/hicolor/}"
                        size="${sizedir%%x*}"
                    fi
                    rsvg-convert -w "$size" -h "$size" "$tmp_svg" -o "$dst"
                else
                    echo "  blueman: rsvg-convert not found, skipping raster icon $f"
                    exit 1
                fi
            elif [[ "$f" == *.svg ]]; then
                sed "s/currentColor/$accent/g" "$f" > "$dst" 2>/dev/null \
                    || cp "$f" "$dst"
            elif [ -n "$tool" ]; then
                "$tool" "$f" -fill "$accent" -colorize 100% "$dst"
            else
                echo "  blueman: no ImageMagick found, skipping raster icon $f"
                exit 1
            fi
            touch "$job_dir/$i"
        ) &
    done
    wait
    patched=$(find "$job_dir" -mindepth 1 | wc -l)
    rm -rf "$job_dir"
    # resolve_themed_svg now always returns a throwaway temp file (never a
    # path under $ICON_DIR), but keep this guard as cheap insurance rather
    # than assume that never changes again.
    case "$tmp_svg" in
        "$ICON_DIR"/*) : ;;   # would be permanent — leave it alone
        "") : ;;
        *) rm -f "$tmp_svg" ;;
    esac
    echo "Blueman tray icons patched ($patched/${#found[@]})"
}

#onedrivegui tray icon
ONEDRIVEGUI_IMAGES_DIR="/usr/lib/OneDriveGUI/resources/images"

declare -A ONEDRIVEGUI_SVG_OVERRIDES=(
    ["icons8-cloud-done-80.png"]="cloud-check:accent"      # ok/synced
    ["warning.png"]="cloud-exclamation:#f39c12"            # warning
    ["icons8-cloud-error-80.png"]="cloud-x:#e74c3c"        # error
    ["icons8-cloud-sync-80.png"]="cloud-cog:accent"        # syncing
)

declare -A ONEDRIVEGUI_COLORIZE_ONLY=(
    ["icons8-cloud-80.png"]="accent"        # idle
    ["icons8-cloud-stop-80.png"]="accent"   # paused (unless this is actually "warning" — see above)
)

fix_onedrivegui_permissions() {
    fix_system_dir_permissions "$ONEDRIVEGUI_IMAGES_DIR" "onedrivegui"
}

patch_onedrivegui_tray() {
    command -v onedrivegui >/dev/null 2>&1 || return 0
    [ -d "$ONEDRIVEGUI_IMAGES_DIR" ] || {
        echo "  onedrivegui: $ONEDRIVEGUI_IMAGES_DIR not found (package layout may have changed)"
        return 1
    }

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "onedrivegui: custom SVG replacements:"
        for name in "${!ONEDRIVEGUI_SVG_OVERRIDES[@]}"; do
            IFS=':' read -r icon_name target <<< "${ONEDRIVEGUI_SVG_OVERRIDES[$name]}"
            [ "$target" = "accent" ] && target="$accent"
            printf '  %-28s -> %s_base_icon.svg (%s)\n' "$name" "$icon_name" "$target"
        done
        echo "onedrivegui: plain recolor (existing vendor art):"
        for name in "${!ONEDRIVEGUI_COLORIZE_ONLY[@]}"; do
            local target="${ONEDRIVEGUI_COLORIZE_ONLY[$name]}"
            [ "$target" = "accent" ] && target="$accent"
            printf '  %-28s -> %s\n' "$name" "$target"
        done
        echo "  (left alone: icons8-green-circle-48.png, icons8-red-circle-48.png, and"
        echo "   in-window UI icons like account/folder/gear/play/pause/quit)"
        return 0
    fi

    local tool=""
    command -v magick >/dev/null 2>&1 && tool="magick"
    [ -z "$tool" ] && command -v convert >/dev/null 2>&1 && tool="convert"
    if [ -z "$tool" ]; then
        echo "  onedrivegui: ImageMagick not found, cannot recolor icons"
        return 1
    fi
    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  onedrivegui: rsvg-convert not found, cannot rasterize custom SVGs"
        return 1
    }

    fix_onedrivegui_permissions || return 1

    local patched=0 skipped=0

    # -- custom SVG replacements --
    for name in "${!ONEDRIVEGUI_SVG_OVERRIDES[@]}"; do
        local f="$ONEDRIVEGUI_IMAGES_DIR/$name"
        [ -f "$f" ] || { echo "  onedrivegui: vendor file $name not found, skipping"; continue; }

        IFS=':' read -r icon_name target <<< "${ONEDRIVEGUI_SVG_OVERRIDES[$name]}"
        [ "$target" = "accent" ] && target="$accent"

        local src_svg="$ICONS/${icon_name}_base_icon.svg"
        if [ ! -f "$src_svg" ]; then
            echo "  onedrivegui: $src_svg not found — add it, or drop this override for $name"
            skipped=$((skipped + 1))
            continue
        fi

        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"

        # Match the vendor icon's own pixel size so it doesn't look
        # mismatched next to the icons we're leaving alone.
        local dims
        if command -v identify >/dev/null 2>&1; then
            dims=$(identify -format "%wx%h" "$backup" 2>/dev/null)
        else
            dims=$("$tool" identify -format "%wx%h" "$backup" 2>/dev/null)
        fi
        local w="${dims%x*}" h="${dims#*x}"
        [ -z "$w" ] && w=80
        [ -z "$h" ] && h=80

        local tmp_svg tmp_png
        tmp_svg=$(mktemp --suffix=.svg)
        tmp_png=$(mktemp --suffix=.png)
        sed "s/currentColor/$target/g" "$src_svg" > "$tmp_svg"
        rsvg-convert -w "$w" -h "$h" "$tmp_svg" -o "$tmp_png"
        cp "$tmp_png" "$f"
        rm -f "$tmp_svg" "$tmp_png"
        patched=$((patched + 1))
        echo "  $name replaced with ${icon_name}_base_icon.svg ($target)"
    done

    # -- plain recolor of remaining vendor art --
    for name in "${!ONEDRIVEGUI_COLORIZE_ONLY[@]}"; do
        local f="$ONEDRIVEGUI_IMAGES_DIR/$name"
        [ -f "$f" ] || { echo "  onedrivegui: vendor file $name not found, skipping"; continue; }

        local target="${ONEDRIVEGUI_COLORIZE_ONLY[$name]}"
        [ "$target" = "accent" ] && target="$accent"

        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"

        "$tool" "$backup" -fill "$target" -colorize 100% "$f"
        patched=$((patched + 1))
    done

    echo "OneDriveGUI tray icons patched ($patched patched, $skipped skipped)"
    echo "  (originals preserved as *.png.orig next to each file)"
}

#vesktop tray icons
patch_vesktop_tray() {
    command -v vesktop >/dev/null 2>&1 || return 0

    local user_assets="$HOME/.config/vesktop/userAssets"

    # Don't create userAssets/ ourselves if Vesktop has never initialized
    # it — writing files there before Vesktop knows about custom assets
    # at all may not be picked up. Ask once via the UI (Customize ->
    # pick any file, for both Tray and Tray Unread) so Vesktop creates
    # its own tray/trayUnread files, then this script just keeps
    # overwriting them from then on.
    [ -d "$user_assets" ] || {
        echo "  vesktop: $user_assets doesn't exist yet — open Vesktop's"
        echo "  Settings -> User Assets -> Tray/Tray Unread -> Customize"
        echo "  and pick any image once for each, then re-run this script."
        return 1
    }

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  vesktop: rsvg-convert not found, cannot rasterize"; return 1
    }

    local patched=0

    # -- plain tray icon --
    local svg
    svg=$(resolve_themed_svg "vesktop") || svg=$(resolve_themed_svg "discord") || {
        echo "  vesktop: no themed base icon found for tray, skipping"
    }
    if [ -n "$svg" ]; then
        local target="$user_assets/tray"
        if [ "$LIST_ONLY" -eq 1 ]; then
            echo "vesktop: would overwrite $target"
        else
            rsvg-convert -w 64 -h 64 "$svg" -o "$target" \
                && { echo "Vesktop tray icon patched in place ($target)"; patched=$((patched + 1)); }
        fi
    fi

    # -- unread-badge variant — separate base icon, since the badge is
    # baked into the artwork itself rather than composited by Vesktop
    # (unlike Ferdium/OneDriveGUI, there's no separate dot overlay step
    # here — whatever discord-unread_base_icon.svg draws is exactly what
    # shows in the tray). --
    local svg_unread
    svg_unread=$(resolve_themed_svg "discord-unread") || {
        echo "  vesktop: discord-unread_base_icon.svg not found, skipping trayUnread"
    }
    if [ -n "$svg_unread" ]; then
        local target_unread="$user_assets/trayUnread"
        if [ "$LIST_ONLY" -eq 1 ]; then
            echo "vesktop: would overwrite $target_unread"
        else
            rsvg-convert -w 64 -h 64 "$svg_unread" -o "$target_unread" \
                && { echo "Vesktop trayUnread icon patched in place ($target_unread)"; patched=$((patched + 1)); }
        fi
    fi

    [ "$LIST_ONLY" -eq 1 ] && return 0
    [ "$patched" -gt 0 ]
}

#ytmdesktop tray icons
patch_ytmdesktop_tray() {
    local resource_dir=""
    local candidates=(
        "/opt/ytmdesktop/resources"
        "/opt/YouTube Music Desktop App/resources"
        "/usr/lib/ytmdesktop/resources"
    )
    local d
    for d in "${candidates[@]}"; do
        if [ -f "$d/ytmd_white.png" ] && [ -f "$d/ytmd_black.png" ]; then
            resource_dir="$d"
            break
        fi
    done
    [ -n "$resource_dir" ] || {
        echo "  ytmdesktop: ytmd_white.png/ytmd_black.png not found under any of:"
        printf '    %s\n' "${candidates[@]}"
        echo "  (package layout may differ — find them with:"
        echo "   find / -name 'ytmd_white.png' 2>/dev/null)"
        return 1
    }

    local svg
    svg=$(resolve_themed_svg "music") || { echo "  ytmdesktop: music_base_icon.svg not found, skipping tray"; return 1; }

    local targets=("$resource_dir/ytmd_white.png" "$resource_dir/ytmd_black.png")

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "ytmdesktop: would overwrite:"
        printf '  %s\n' "${targets[@]}"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  ytmdesktop: rsvg-convert not found, cannot rasterize"; return 1
    }
    fix_system_dir_permissions "$resource_dir" "ytmdesktop" || return 1

    local patched=0
    local f
    for f in "${targets[@]}"; do
        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"
        # Match the original 512x512 canvas so the tray-side downscale
        # behaves the same as upstream's own icon.
        rsvg-convert -w 512 -h 512 "$svg" -o "$f" && patched=$((patched + 1))
    done
    echo "YTMDesktop tray icons patched in place ($patched/${#targets[@]}, $resource_dir)"

    [ "$patched" -gt 0 ] && ytmdesktop_force_reload
}

# Makes one durable change to trayIconStyle in YTMDesktop's own config.json
# so its `conf` store — polling via fs.watchFile on Linux, see the long
# comment above — actually notices it and calls setTrayIcon() itself,
# re-reading the PNGs we just overwrote. Values: Auto=0, White=1, Black=2
# (src/shared/store/schema.ts). Schedules a delayed, detached revert back
# to your real setting — cosmetic only, since ytmd_white.png and
# ytmd_black.png are now identical, so which one gets selected doesn't
# change what's actually drawn in the tray.
ytmdesktop_force_reload() {
    { pgrep -x youtube-music-desktop-app >/dev/null 2>&1 || pgrep -f ytmdesktop >/dev/null 2>&1; } || {
        echo "  ytmdesktop: not currently running, nothing to notify"
        return 0
    }
    command -v jq >/dev/null 2>&1 || {
        echo "  ytmdesktop: jq not found, can't trigger a live tray refresh"
        echo "  (new icons will show next time YTMDesktop starts)"
        return 1
    }

    local cfg="$HOME/.config/YouTube Music Desktop App/config.json"
    [ -f "$cfg" ] || {
        echo "  ytmdesktop: config.json not found at $cfg, can't trigger a live refresh"
        return 1
    }

    local current other tmp
    current=$(jq -r '.appearance.trayIconStyle // 0' "$cfg")
    other=$(( (current + 1) % 3 ))

    tmp=$(mktemp)
    jq ".appearance.trayIconStyle = $other" "$cfg" > "$tmp" && mv "$tmp" "$cfg"
    echo "  ytmdesktop: set trayIconStyle $current -> $other to force a live repaint"
    echo "  (conf polls the file on Linux — can take up to ~10s to actually redraw)"

    # Detached: this script's own run finishes long before the revert
    # fires, no need to make the theme refresh wait ~10+ more seconds on
    # a cosmetic settings-value cleanup.
    (
        sleep 12
        tmp2=$(mktemp)
        jq ".appearance.trayIconStyle = $current" "$cfg" > "$tmp2" 2>/dev/null && mv "$tmp2" "$cfg"
    ) >/dev/null 2>&1 &
    disown
}

#betterbird tray icons
betterbird_tray_patch() {
    local betterbirdTarget isFlatpak=0

    if [ -d "$HOME/.var/app/eu.betterbird.Betterbird" ]; then
        isFlatpak=1
        betterbirdTarget="$HOME/.var/app/eu.betterbird.Betterbird/data/icons/hicolor/scalable/status"
    elif command -v betterbird >/dev/null 2>&1; then
        betterbirdTarget="/opt/betterbird"
    else
        echo "  betterbird: not installed, skipping tray"
        return 0
    fi

    defaultsvg=$(resolve_themed_svg "mail") || { echo "  betterbird: no themed base icon found, skipping tray"; return 1; }
    newmailsvg=$(resolve_themed_svg "new-mail") || { echo "  betterbird: no themed new-mail icon found, skipping tray"; return 1; }

    if [ "$isFlatpak" -eq 1 ]; then
        if [ "$LIST_ONLY" -eq 1 ]; then
            echo "betterbird: would overwrite:"
            echo "  $betterbirdTarget/eu.betterbird.Betterbird-default.svg"
            echo "  $betterbirdTarget/eu.betterbird.Betterbird-newmail.svg"
            return 0
        fi
        mkdir -p "$betterbirdTarget" || return 1
        cp "$defaultsvg" "$betterbirdTarget/eu.betterbird.Betterbird-default.svg"
        cp "$newmailsvg" "$betterbirdTarget/eu.betterbird.Betterbird-newmail.svg"
        echo "Betterbird tray icon patched (flatpak)"
        return 0
    fi

    cp "$defaultsvg" "$betterbirdTarget/chrome/icons/default/default.svg"
    cp "$newmailsvg" "$betterbirdTarget/chrome/icons/default/newmail.svg"

    local svg
    svg=$(resolve_themed_svg "mail") || { echo "  betterbird: no themed base icon found, skipping tray"; return 1; }

    local targets=(
        "$betterbirdTarget/chrome/icons/default/default16.png"
        "$betterbirdTarget/chrome/icons/default/default22.png"
        "$betterbirdTarget/chrome/icons/default/default24.png"
        "$betterbirdTarget/chrome/icons/default/default32.png"
        "$betterbirdTarget/chrome/icons/default/default48.png"
        "$betterbirdTarget/chrome/icons/default/default64.png"
        "$betterbirdTarget/chrome/icons/default/default128.png"
        "$betterbirdTarget/chrome/icons/default/default256.png"
    )

    local resolutions=(
        16 22 24 32 48 64 128 256
    )

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "betterbird: would overwrite:"
        printf '  %s\n' "${targets[@]}"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  betterbird: rsvg-convert not found, cannot rasterize"; return 1
    }
    fix_system_dir_permissions "$betterbirdTarget/chrome/icons/default" "default.svg" || return 1

    local patched=0
    for r in "${resolutions[@]}"; do
        local f="$betterbirdTarget/chrome/icons/default/default${r}.png"
        [ -f "$f" ] || { echo "  betterbird: $f not found, skipping"; continue; }
        local backup="${f}.orig"
        [ -f "$backup" ] || cp "$f" "$backup"
        rsvg-convert -w $r -h $r "$svg" -o "$f" && patched=$((patched + 1))
    done
    echo "Betterbird tray icon patched in place ($patched/${#targets[@]})"
}

#cohesion tray icons
cohesion_tray_patch() {
    local app_id="io.github.brunofin.Cohesion"
    command -v flatpak >/dev/null 2>&1 || return 0
    flatpak info "$app_id" >/dev/null 2>&1 || return 0

    local override_dir="$HOME/.local/share/cohesion-icons"
    local icon_dir="$override_dir/icons/hicolor/512x512/apps"

    # One-time sandbox grant, checked (not blindly re-applied) every run so
    # this doesn't spam `flatpak override` on every theme refresh — same
    # spirit as fix_system_dir_permissions's one-time chown above.
    if ! flatpak override --user --show "$app_id" 2>/dev/null | grep -q "$override_dir"; then
        echo "  cohesion: granting one-time sandbox access to $override_dir"
        flatpak override --user "$app_id" \
            --filesystem="$override_dir:ro" \
            --env=XDG_DATA_DIRS="$override_dir:/app/share:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share" \
            || { echo "  cohesion: flatpak override failed, skipping tray"; return 1; }
    fi

    mkdir -p "$icon_dir" || return 1

    local svg
    svg=$(resolve_themed_svg "notion") || {
        echo "  cohesion: no themed base icon found ($ICONS/cohesion_base_icon.svg), skipping tray"
        return 1
    }

    local color_targets=(
        "$icon_dir/io.github.brunofin.Cohesion.png"
        "$icon_dir/io.github.brunofin.Cohesion-unread.png"
    )
    local grey_targets=(
        "$icon_dir/io.github.brunofin.Cohesion-greyscale.png"
        "$icon_dir/io.github.brunofin.Cohesion-greyscale-unread.png"
    )

    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "cohesion: would write:"
        printf '  %s\n' "${color_targets[@]}" "${grey_targets[@]}"
        return 0
    fi

    command -v rsvg-convert >/dev/null 2>&1 || {
        echo "  cohesion: rsvg-convert not found, cannot rasterize"; return 1
    }

    local patched=0
    local f
    for f in "${color_targets[@]}"; do
        rsvg-convert -w 512 -h 512 "$svg" -o "$f" && patched=$((patched + 1))
    done

    # Greyscale slots are Cohesion's own monochrome tray-style toggle —
    # desaturate the accent render rather than reusing it verbatim, so the
    # toggle still does something. ${f/-greyscale/} maps each greyscale
    # target back to the color file it should be derived from (...
    # -greyscale.png -> ...png, ...-greyscale-unread.png -> ...-unread.png).
    if command -v magick >/dev/null 2>&1; then
        for f in "${grey_targets[@]}"; do
            magick "${f/-greyscale/}" -colorspace Gray "$f" && patched=$((patched + 1))
        done
    elif command -v convert >/dev/null 2>&1; then
        for f in "${grey_targets[@]}"; do
            convert "${f/-greyscale/}" -colorspace Gray "$f" && patched=$((patched + 1))
        done
    else
        echo "  cohesion: imagemagick not found, copying color icon into greyscale slots unmodified"
        for f in "${grey_targets[@]}"; do
            cp "${f/-greyscale/}" "$f" && patched=$((patched + 1))
        done
    fi

    echo "Cohesion tray icons patched ($patched/4, $icon_dir)"
    echo "  (restart Cohesion for the new icons to take effect)"
}

#obs tray icons
patch_obs_tray() {
    local is_native=0 is_flatpak=0
    command -v obs >/dev/null 2>&1 && is_native=1 && echo "  obs: native build detected"
    flatpak info com.obsproject.Studio >/dev/null 2>&1 && is_flatpak=1 && echo "  obs: flatpak build detected"
    { [ "$is_native" -eq 1 ] || [ "$is_flatpak" -eq 1 ]; } || return 0
 
    if [ "$is_flatpak" -eq 1 ]; then
        # One-time, checked (not blindly re-applied) every run — same
        # pattern as cohesion_tray_patch's override gate above.
        if ! flatpak override --user --show com.obsproject.Studio 2>/dev/null | grep -q "$HOME/.local/share"; then
            echo "  obs: granting one-time XDG_DATA_DIRS override for the flatpak build"
            flatpak override --user com.obsproject.Studio \
                --env=XDG_DATA_DIRS="$HOME/.local/share:/app/share:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share" \
                || echo "  obs: flatpak override failed, tray icon may still not resolve"
        fi
    fi
 
    local recording_svg
    local idle_svg
    recording_svg=$(resolve_themed_svg "obs-recording") || {
        echo "  obs: no themed recording base icon found ($ICONS/obs-recording_base_icon.svg), skipping tray"
        return 1
    }
    idle_svg=$(resolve_themed_svg "obs") || {
        echo "  obs: no themed idle base icon found ($ICONS/obs_base_icon.svg), skipping tray"
        return 1
    }
 
    local target_dir="$ICON_DIR/status/scalable"
    local targets=(
        "$target_dir/obs-tray.svg"
        "$target_dir/obs-tray-active.svg"
    )
 
    if [ "$LIST_ONLY" -eq 1 ]; then
        echo "obs: would write (native=$is_native, flatpak=$is_flatpak):"
        printf '  %s\n' "${targets[@]}"
        return 0
    fi
 
    mkdir -p "$target_dir" || return 1
    fix_system_dir_permissions "$target_dir" "obs" || return 1
 
    local patched=0
    cp "$idle_svg" "$target_dir/obs-tray.svg" && patched=$((patched + 1))
    cp "$recording_svg" "$target_dir/obs-tray-active.svg" && patched=$((patched + 1))
 
    echo "OBS tray icons patched ($patched/2, $target_dir)"
    echo "  (icon theme cache may need a refresh — or just restart OBS — for the new lookup to take effect)"
}


# time_step <label> <function> — runs the given function, prints its
# wall-clock time to stderr afterward. awk instead of bc for the float
# subtraction so this doesn't need an extra package installed.
time_step() {
    local label="$1"; shift
    local start end
    start=$(date +%s.%N)
    "$@"
    end=$(date +%s.%N)
    awk -v s="$start" -v e="$end" -v l="$label" \
        'BEGIN { printf "  [%7.3fs] %s\n", e - s, l }' >&2
}

# ---- Run everything ----
time_step "nativmix"        patch_nativmix_tray
time_step "ferdium"         patch_ferdium_tray
time_step "localsend"       patch_localsend_tray
time_step "streamcontroller" patch_streamcontroller_tray
time_step "steam"           patch_steam_tray
time_step "blueman"         patch_blueman_tray
time_step "onedrivegui"     patch_onedrivegui_tray
time_step "vesktop"         patch_vesktop_tray
time_step "ytmdesktop"      patch_ytmdesktop_tray
time_step "betterbird"      betterbird_tray_patch
time_step "cohesion"        cohesion_tray_patch
time_step "obs"             patch_obs_tray

[ "$LIST_ONLY" -eq 0 ] && echo "Tray icons patched with $accent"