#!/usr/bin/env bash
# zenPatcher.sh
# Patches Zen Browser chrome with the accent color.
# Usage: zenPatcher.sh <hex_color>

color="${1,,}"

if [ -z "$color" ]; then
    echo "Usage: $0 <hex_color>" >&2
    exit 1
fi

accent="#$color"

for ZEN_PROFILE in "$HOME/.zen/8ma66p8a.Default (release)" "$HOME/.zen/k71gdxvw.Default Profile"; do
    [ ! -d "$ZEN_PROFILE" ] && continue
    mkdir -p "$ZEN_PROFILE/chrome"
    cat > "$ZEN_PROFILE/chrome/userChrome.css" << EOF
/* Generated by themeRefresher */
:root {
    --lwt-accent-color: $accent !important;
    --toolbar-field-focus-border-color: $accent !important;
    --toolbar-field-color: #fcfcfc !important;
    --toolbar-field-focus-color: #fcfcfc !important;
    --toolbar-color: #fcfcfc !important;
    --urlbar-box-text-color: #fcfcfc !important;
}
#urlbar-input { color: #fcfcfc !important; }
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    cat > "$ZEN_PROFILE/chrome/userContent.css" << EOF
/* Generated by themeRefresher */
::selection { background-color: $accent !important; color: #ffffff !important; }
EOF
    grep -q "toolkit.legacyUserProfileCustomizations.stylesheets" "$ZEN_PROFILE/prefs.js" 2>/dev/null || \
        echo 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$ZEN_PROFILE/prefs.js"
    echo "Zen profile patched: $ZEN_PROFILE"
done
